spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/hishabi_dev
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

springdoc:
    swagger-ui:
        path: /api/v1/swagger-ui/index.html

    api-docs:
        path: /v3/api-docs
